version: '3.8'
services:
  nodejs:
    image: node:${NODE_VERSION}
    ports:
      - "3000:3000"
      - "1337:1337"
    environment:
      NODE_ENV: development
    command: bash -c "npm install depcheck --location=global  --force && sleep infinity"
    tty: true
    working_dir: '/var/www/html'
    volumes:
      - '../backend/.:/var/www/html/cms'
      - '../frontend/.:/var/www/html'
      - '../oldBlog/.:/var/www/html/oldBlog'
    networks:
      - node
    container_name: ${APP_NAME}_nodejs

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: unless-stopped
    container_name: ${APP_NAME}_postgres

networks:
  node:
    driver: bridge
volumes:
  postgres:
     driver: local

